name: Pull request

on:
  pull_request:
    types:
      - opened

jobs:
  pr-integration:
    runs-on: ubuntu-latest
    env:
      INSTALLATION_TOKEN: TO_BE_DETERMINED
    steps:
      - name: dump github context
        run: |
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: integrate the pull request with backlog
        if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
        uses: kazamori/backlog-github-integration-action@main
        with:
          subcommand: "pull_request"
          args: "--repository ${{ github.repository }} --pr-number ${{ github.event.number }}"
        env:
          APP_LOCALE: "en_US"
          APP_LOG_LEVEL: "debug"
          BACKLOG_FQDN: ${{ secrets.BACKLOG_FQDN }}
          BACKLOG_API_KEY: ${{ secrets.BACKLOG_API_KEY }}
          BACKLOG_PROJECT_KEY: ${{ secrets.BACKLOG_PROJECT_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
